app:
  topic:
    name: equities
    
    
kafka:
  producer:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8080

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
